### ISSUE TITLE
CRC (or missing _id value) error in midea-

### ISSUE THREAD

**Issue by csipeter** [mac-zhou/midea-msmart#103]
Hello!

My environment is Debian 11.5 python 3.9
I'm not python expert neither hardwer investigator so I need some help to set my AC.
Please Help!

I got following error when run your discover script:
`
midea-discover -d -i 192.168.aaa.bbb -a c********@gmail.com -p ********
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.2.5 Currently only supports ac devices, only support MSmartHome and 美的美居 APP.
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:msmart.scanner:Message sent
DEBUG:msmart.scanner:Midea Local Data 192.168.aaa.bbb 
a5a011178007a8000000000000000000000000036190000000a00000000000000000000010000002828fd243060299fca4bd4d874d2490debf1935e6fb213b118d69ba4654adb8752639fd1b76b6662b32afb070a4732a9ca1fca21cfa6c05c4d1e2f008dc5b4dd7c8cad70412d8bc5eee2717a381efaae
DEBUG:msmart.scanner:Decrypt Reply: 192.168.aaa.bbb d86ea8c02c19000030303030303050303030303030305131424330463242413145304134303030300b6e65745f61635f45304134
DEBUG:msmart.base_command:Frame data: aa21ac8d000000000003418100ff03ff000200000000000000000000000003016971
DEBUG:msmart.device.base:pkt_builder: 192.168.aaa.bbb:6444 len: 104 data: 5a5a0111680020000000000047120109040c161436190000000a0000000000000000000000000000b8436dd15e84d5a4fc6fbf77d2b12486e10c552981b23022cb71ea0fc54dc25ecfa0ce55888ac57fc42a7eacc3285d37bf528687170784ab1da604a2f82e214a
DEBUG:msmart.lan:Attempting new connection to 192.168.aaa.bbb:6444
DEBUG:msmart.lan:Socket 192.168.aaa.ccc:50154 -> 192.168.aaa.bbb:6444 retries: 0 time: 0.0 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.aaa.ccc:50154 -> 192.168.aaa.bbb:6444 retries: 0 time: 0.0 message: 5a5a0111680020000000000047120109040c161436190000000a0000000000000000000000000000b8436dd15e84d5a4fc6fbf77d2b12486e10c552981b23022cb71ea0fc54dc25ecfa0ce55888ac57fc42a7eacc3285d37bf528687170784ab1da604a2f82e214a
DEBUG:msmart.lan:Recv 192.168.aaa.ccc:50154 -> 192.168.aaa.bbb:6444 retries: 0 time: 2.0, timed out
DEBUG:msmart.lan:Get responses len: 0
DEBUG:msmart.lan:Socket 192.168.aaa.ccc:50154 -> 192.168.aaa.bbb:6444 retries: 1 time: 3.0 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.aaa.ccc:50154 -> 192.168.aaa.bbb:6444 retries: 1 time: 3.01 message: 5a5a0111680020000000000047120109040c161436190000000a0000000000000000000000000000b8436dd15e84d5a4fc6fbf77d2b12486e10c552981b23022cb71ea0fc54dc25ecfa0ce55888ac57fc42a7eacc3285d37bf528687170784ab1da604a2f82e214a
DEBUG:msmart.lan:Recv 192.168.aaa.ccc:50154 -> 192.168.aaa.bbb:6444 retries: 1 time: 3.01 Response: 5a5a01115800208000000000000000000000000036190000000a0000000000000000000001000000dde6a077cdfe0447ead87f980296801981410957d04daa24124acb945c6d94958e6185bde4f67b0db00161e688c42e4f
DEBUG:msmart.lan:Get responses len: 88
DEBUG:msmart.device.base:Got responses from 192.168.aaa.bbb:6444 Version: 2 Count: 1 Spend time: 3.02
DEBUG:msmart.device.base:Update from 192.168.aaa.bbb:6444 aa1eac00000000000003c00088667f7f00000000006138000000000000bb33
ERROR:msmart.device.AC.command:Payload 'c00088667f7f00000000006138000000000000bb' failed CRC. Received: 0xBB, Expected: 0x22.
Traceback (most recent call last):
  File "/usr/local/bin/midea-discover", line 8, in <module>
    sys.exit(discover())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/msmart/cli.py", line 51, in discover
    found_devices = loop.run_until_complete(discovery.get_all() if ip == '' else discovery.get(ip))
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 205, in get
    await self._process_tasks([task])
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 199, in _process_tasks
    [self.result.add(task.result()) for task in tasks]
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 199, in <listcomp>
    [self.result.add(task.result()) for task in tasks]
  File "/usr/local/lib/python3.9/dist-packages/msmart/scanner.py", line 55, in support_test
    await loop.run_in_executor(None, _device.refresh)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/dist-packages/msmart/device/AC/appliance.py", line 109, in refresh
    self._send_cmd(cmd)
  File "/usr/local/lib/python3.9/dist-packages/msmart/device/AC/appliance.py", line 114, in _send_cmd
    self._process_response(response)
  File "/usr/local/lib/python3.9/dist-packages/msmart/device/AC/appliance.py", line 124, in _process_response
    if response.id == ResponseId.State:
  File "/usr/local/lib/python3.9/dist-packages/msmart/device/AC/command.py", line 206, in id
    return self._id
AttributeError: 'state_response' object has no attribute '_id'
`

**Comment by nixmeer** [comment]
Same [here](https://github.com/mac-zhou/midea-msmart/issues/104#issuecomment-1479740312)

**Comment by SpasovskiFilip** [comment]
I have the same [issue here ](https://github.com/mill1000/midea-ac-py/issues/11#issuecomment-1650647625)

**Comment by mill1000** [comment]
This issue has been fixed in my fork: [mill1000/midea-msmart](https://github.com/mill1000/midea-msmart)
