### ISSUE TITLE
SyntaxError: invalid syntax when running midea-discover

### ISSUE THREAD

**Issue by jasongaunt** [mac-zhou/midea-msmart#40]
Hi @mac-zhou  

I get the following error when I try and run `midea-discover`:

```python
Traceback (most recent call last):
  File "/usr/local/bin/midea-discover", line 7, in <module>
    from msmart.cli import discover
  File "/usr/local/lib/python3.5/dist-packages/msmart/cli.py", line 3, in <module>
    import click
  File "/usr/local/lib/python3.5/dist-packages/click/__init__.py", line 7, in <module>
    from .core import Argument as Argument
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 95
    f"{hint}. Command {base_command.name!r} is set to chain and"
                                                               ^
SyntaxError: invalid syntax
```

This is running as root on Ubuntu 16.04.7 LTS with Python 3.5.2, installed using `pip3 install msmart`.

Please can you advise?

**Comment by 0xbw** [comment]
upgrade `pip3 install click==7.1.2` and try again

**Comment by jasongaunt** [comment]
Hi @mac-zhou - this fixed the issue, many thanks ♥
