### ISSUE TITLE
ERROR:msmart.security:authentication failed

### ISSUE THREAD

**Issue by jacob2826** [mac-zhou/midea-msmart#75]
midea-discover -cn -i 192.168.**.*** -a 1********** -p ********
INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome and 美的美居 APP.
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.smartmidea.net/mas/v5/app/proxy?alias= True
ERROR:msmart.security:authentication failed
ERROR:msmart.lan:Authentication failed for 192.168.**.***:56074 -> 192.168.**.***:6444 retries: 0 time: 0.05
Traceback (most recent call last):
  File "/Users/jacob/anaconda/bin/midea-discover", line 11, in <module>
    load_entry_point('msmart==0.2.3', 'console_scripts', 'midea-discover')()
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/cli.py", line 51, in discover
  File "/Users/jacob/anaconda/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 205, in get
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 199, in _process_tasks
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 199, in <listcomp>
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 50, in support_test
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 66, in support_testv3
  File "/Users/jacob/anaconda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/device/base.py", line 38, in authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/device/base.py", line 42, in _authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/lan.py", line 113, in authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/security.py", line 112, in tcp_key
TypeError: argument 2 must be bytes, not bytearray

**Comment by jacob2826** [comment]
I have 2 ACs under the same Wi-Fi.

**Comment by 0xbw** [comment]
> I have 2 ACs under the same Wi-Fi.

try again

**Comment by jacob2826** [comment]
> 

Still not working. Same error "TypeError: argument 2 must be bytes, not bytearray".

**Comment by 0xbw** [comment]
please enable debug mode, then show me the output
 `midea-discover -cn -i 192.168..* -a 1********** -p ******** -d`

**Comment by jacob2826** [comment]
@mac-zhou Here's the debug-mode output. It seems that the script has acquired the token? 

> INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome and 美的美居 APP.
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:msmart.scanner:Broadcast message sent: 1
DEBUG:msmart.scanner:Midea Local Data 192.168.99.214 837000c8200f00005a5a0111b8007a8000000000a23a040b0f0516148287040000a70000000000000000018000000000c87456434628c52a97c41c5f4d41faf97c678b2b19a0b85bc2d726e66d8f471161679dcd6dafee4619b8dfabf2f0c170c9d5d2d3aa692e1cd9e1d469da060756c2c51bd40416e14d14b68381d232691622808d22bec732f945ff4ce853e8afe84bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e7d6ef38acf156340687d7dcac8284fb09da3dadfc10a7eeeca8f555a11b2a7a20
DEBUG:msmart.scanner:Decrypt Reply: 192.168.99.214 d663a8c02c19000030303030303033313132323031323539333141323930353330373536303030300d6d696465615f61635f303735360000870002000000000000000000ac00acac0000000004d6f4d617c4150016092051000300000000000000000000000000000000000000000000000000000000000000000000
DEBUG:msmart.scanner:Midea Local Data 192.168.99.213 837000c8200f00005a5a0111b8007a8000000000a83a040b0f051614b17d040000a10000000000000000018000000000e375684c51ba68dab7128eb3037e9daa7c678b2b19a0b85bc2d726e66d8f4711ee5f5e8c971b293ad256c4e00493d69196577fc4b23c562afc9e957b5f538d5834b11552110dc1b2c2368f9bfe55c31eac3322c93567c848eaaff554ca88504a4bdfb3e16e33d88768cc4c3d0658937d96fbcce99f70c976413c2f05f60f82e7ef992e6fd12b2f0844df976b55144e350001bb90d3401a809fee4e56ed4c294f
DEBUG:msmart.scanner:Decrypt Reply: 192.168.99.213 d563a8c02c19000030303030303033313132323031323539333141323930353330363434303030300d6d696465615f61635f303634340000870002000000000000000000ac00acac0000000004d6f4d78360150016092051000300000000000000000000000000000000000000000000000000000000000000000000
DEBUG:msmart.scanner:Socket timeout
INFO:msmart.cloud:Using Midea cloud server: https://mp-prod.smartmidea.net/mas/v5/app/proxy?alias= True
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.smartmidea.net:443
DEBUG:urllib3.connectionpool:https://mp-prod.smartmidea.net:443 "POST /mas/v5/app/proxy?alias=/v1/user/login/id/get HTTP/1.1" 200 75
DEBUG:msmart.cloud:Response: {"code":0,"msg":null,"data":{"loginId":"b36d15e06238457aa4bdc69be9367efe"}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.smartmidea.net:443
DEBUG:urllib3.connectionpool:https://mp-prod.smartmidea.net:443 "POST /mas/v5/app/proxy?alias=/mj/user/login HTTP/1.1" 200 1204
DEBUG:msmart.cloud:Response: {"code":0,"msg":"成功","data":{"uid":"dd817b9070c34534b0d9daa93a660114","userInfo":{"birthday":null,"mail":null,"signature":null,"homeName":null,"phone2":null,"phone3":null,"uid":"dd817b9070c34534b0d9daa93a660114","homeCode":null,"isWeixin":"0","cardid":null,"isQq":"0","brand":"1","isApple":"0","registerTime":"1591015927000","nickName":"0662","sex":null,"mobile":"1**********","userId":"1116886568552","headImgUrl":"https://fcmms.midea.com/ccrm-beta/userHeadImg/defaultHeadImg.png","phone":null,"name":null,"mipUser":null,"isUpdateCacheTime":1,"age":null,"account":null},"iotUserId":20242868,"mdata":{"tokenPwdInfo":{"tokenPwd":"e44dd540f7844a2392757860e3153d4a","expiredDate":1655175904095,"createDate":1652583904095},"userInfo":{"sourceId":"mj_12345","empId":"3756231648584704","address":"","gender":"0","mobile":"1**********","userDeptInfoList":null,"extras":null,"nameEn":null,"employeeNumber":null,"headPhoto":null,"uid":"dd817b9070c34534b0d9daa93a660114","name":"1**********","email":null},"doDeviceBind":null,"accessToken":"T1ax1d1ahdds2zg5t","signUnlockEnabled":null},"jwtToken":null,"clusterId":65793,"isOldUse":null,"key":"1665837c3426a54d9f16b0690290762a187c944f79041a1b4b632650e1b4aed9"}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.smartmidea.net:443
DEBUG:urllib3.connectionpool:https://mp-prod.smartmidea.net:443 "POST /mas/v5/app/proxy?alias=/v1/iot/secure/getToken HTTP/1.1" 200 301
DEBUG:msmart.cloud:Response: {"code":0,"msg":null,"data":{"tokenlist":[{"udpId":"662b6267eb3646a930376b8bc050b6b8","key":"DBB4E3D23109404384588F2F66582564C43503205C9C46C392107A2EA2895557","token":"C0C409B25D9CDA458E9B2ED851D4BAC5BB1134965FB2A5B0AE374C48481BE6F41E4928503E415C40CF3C825E5C0BD22098AD5B5F1D6F36AF4892A48A7C038872"}]}}
DEBUG:msmart.lan:Attempting new connection to 192.168.99.214:6444
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.smartmidea.net:443
DEBUG:msmart.lan:Socket 192.168.99.172:54143 -> 192.168.99.214:6444 retries: 0 time: 0.0 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.99.172:54143 -> 192.168.99.214:6444 retries: 0 time: 0.0 message: 8370004020000000c0c409b25d9cda458e9b2ed851d4bac5bb1134965fb2a5b0ae374c48481be6f41e4928503e415c40cf3c825e5c0bd22098ad5b5f1d6f36af4892a48a7c038872
DEBUG:msmart.lan:Recv 192.168.99.172:54143 -> 192.168.99.214:6444 retries: 0 time: 0.05 Response: 83700005200f42304552524f52
ERROR:msmart.security:authentication failed
ERROR:msmart.lan:Authentication failed for 192.168.99.172:54143 -> 192.168.99.214:6444 retries: 0 time: 0.05
DEBUG:urllib3.connectionpool:https://mp-prod.smartmidea.net:443 "POST /mas/v5/app/proxy?alias=/v1/iot/secure/getToken HTTP/1.1" 200 301
DEBUG:msmart.cloud:Response: {"code":0,"msg":null,"data":{"tokenlist":[{"udpId":"5a3aa629ed036354c922d9e021d20fd8","key":"30BDBCB7A02747E293247C7073A3D734C2C5138A7B444E9583C4D79A35541C85","token":"6FFB0A1A4BAB4B80F5BB945EF6678C9B83FAB275FC56C5EDD9CD5DCB7BF26F42D35D69F2AE5A08182AFD36352ED9D73597A24682E99647866F9630CEC10B5F8F"}]}}
DEBUG:msmart.lan:Attempting new connection to 192.168.99.213:6444
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.smartmidea.net:443
DEBUG:msmart.lan:Socket 192.168.99.172:54145 -> 192.168.99.213:6444 retries: 0 time: 0.0 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.99.172:54145 -> 192.168.99.213:6444 retries: 0 time: 0.0 message: 83700040200000006ffb0a1a4bab4b80f5bb945ef6678c9b83fab275fc56c5edd9cd5dcb7bf26f42d35d69f2ae5a08182afd36352ed9d73597a24682e99647866f9630cec10b5f8f
DEBUG:msmart.lan:Recv 192.168.99.172:54145 -> 192.168.99.213:6444 retries: 0 time: 0.05 Response: 83700005200f46094552524f52
ERROR:msmart.security:authentication failed
ERROR:msmart.lan:Authentication failed for 192.168.99.172:54145 -> 192.168.99.213:6444 retries: 0 time: 0.05
DEBUG:urllib3.connectionpool:https://mp-prod.smartmidea.net:443 "POST /mas/v5/app/proxy?alias=/v1/iot/secure/getToken HTTP/1.1" 200 301
DEBUG:msmart.cloud:Response: {"code":0,"msg":null,"data":{"tokenlist":[{"udpId":"da3dadfc10a7eeeca8f555a11b2a7a20","key":"C82ED889049E494E9791F17E22CABFB7DA4CECEEFCD34241ADE884321F172E3D","token":"0B7A53E09B8D109C35FB5683CF22FFB75B9C835BF015FB08E9D5786E1B3A1657F12DA486B0D6479619C775671B3F1818BABC64DB183F6CE6D76CBA07581BC3A0"}]}}
DEBUG:msmart.lan:Socket 192.168.99.172:54143 -> 192.168.99.214:6444 retries: 0 time: 0.37 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.99.172:54143 -> 192.168.99.214:6444 retries: 0 time: 0.37 message: 83700040200000010b7a53e09b8d109c35fb5683cf22ffb75b9c835bf015fb08e9d5786e1b3a1657f12da486b0d6479619c775671b3f1818babc64db183f6ce6d76cba07581bc3a0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.smartmidea.net:443
DEBUG:msmart.lan:Recv 192.168.99.172:54143 -> 192.168.99.214:6444 retries: 0 time: 0.37 Response: 8370004020014e496d2b29af5e347dba562ca1a05e467b05a767a240d207c140f5ab0c28397addf76cbbc424bf955afb791950146409babbaa9d9a2d8c4833f3e750565b39a203c1
DEBUG:urllib3.connectionpool:https://mp-prod.smartmidea.net:443 "POST /mas/v5/app/proxy?alias=/v1/iot/secure/getToken HTTP/1.1" 200 301
DEBUG:msmart.cloud:Response: {"code":0,"msg":null,"data":{"tokenlist":[{"udpId":"0001bb90d3401a809fee4e56ed4c294f","key":"6B6D7ED53EE44BDDB63FC58AFA28F722E123A428FE0143D9BD90A45E3DBD77F6","token":"A2E3C520DECD7C65DC27F91E84666FE64D051EC56C2BBA406D2BBAACABF37B34405C071ACE4D0F952404274DBA4F03F57EB2F159096F8C7420E7C2248110A95E"}]}}
DEBUG:msmart.lan:Socket 192.168.99.172:54145 -> 192.168.99.213:6444 retries: 0 time: 0.33 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.99.172:54145 -> 192.168.99.213:6444 retries: 0 time: 0.33 message: 8370004020000001a2e3c520decd7c65dc27f91e84666fe64d051ec56c2bba406d2bbaacabf37b34405c071ace4d0f952404274dba4f03f57eb2f159096f8c7420e7c2248110a95e
DEBUG:msmart.lan:Recv 192.168.99.172:54145 -> 192.168.99.213:6444 retries: 0 time: 0.37 Response: 837000402001dd4b45d1ad0d503e52c9939eac148b7b2565e85b0996693e410f198f37fca37fd80bfb33304772f350f43f7c4f636b2ff5955c6c32bfb84c65e6208addf24684f098
Traceback (most recent call last):
  File "/Users/jacob/anaconda/bin/midea-discover", line 11, in <module>
    load_entry_point('msmart==0.2.3', 'console_scripts', 'midea-discover')()
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/cli.py", line 51, in discover
  File "/Users/jacob/anaconda/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 193, in get_all
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 199, in _process_tasks
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 199, in <listcomp>
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 50, in support_test
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 66, in support_testv3
  File "/Users/jacob/anaconda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/device/base.py", line 38, in authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/device/base.py", line 42, in _authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/lan.py", line 113, in authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/security.py", line 112, in tcp_key
TypeError: argument 2 must be bytes, not bytearray
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<scandevice.support_test() done, defined at /Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py:47> exception=TypeError('argument 2 must be bytes, not bytearray',)>
Traceback (most recent call last):
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 50, in support_test
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/scanner.py", line 66, in support_testv3
  File "/Users/jacob/anaconda/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/device/base.py", line 38, in authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/device/base.py", line 42, in _authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/lan.py", line 113, in authenticate
  File "/Users/jacob/anaconda/lib/python3.6/site-packages/msmart-0.2.3-py3.6.egg/msmart/security.py", line 112, in tcp_key
TypeError: argument 2 must be bytes, not bytearray

**Comment by Kezzsim** [comment]
*EDIT: It works on my Raspberry Pi 4 but not on my iMac*

Hi

I'm getting the same issue involving TypeError but even before providing credentials

Here' is my debug output
```midea-discover -d
INFO:msmart.cli:Debug mode active
INFO:msmart.cli:msmart version: 0.2.3 Currently only supports ac devices, only support MSmartHome APP.
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:msmart.scanner:Broadcast message sent: 1
DEBUG:msmart.scanner:Midea Local Data 192.168.2.103 837000b8200f04055a5a0111a8007a800000000000000000000000000e500100000e0000000000000000000000000000683deb2fffc3ed50cbcc84dd0e304c25a13e92f05e9c53a3523a7fbdd1e80f7c9935fddcea8ea18c3601f6ba2c8c34c5a070b01c4593de2339f8ba1e7aaaef55b555dcf65a7fe6839f22d00f1cf72a5f27894ab6cf71c28b56b12c3c424196e7f31443d17c3aac03a7656614ae1dca44f4ebdf4395dab3a6a836a36a0dcfdfdc6335ee2b5f498cb684ece6449f9ef373
DEBUG:msmart.scanner:Decrypt Reply: 192.168.2.103 6702a8c02c19000030303030303050303030303030305131353032444242383342313537303030300b6e65745f61635f423135370000000001000000040000000000ac00000000000000502dbb83b157069fcd0400020103000000000000000000000000000000000000000000
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mp-prod.appsmb.com:443 "POST /mas/v5/app/proxy?alias=/v1/user/login/id/get HTTP/1.1" 200 77
DEBUG:msmart.cloud:Response: {"code":"0","msg":"ok","data":{"loginId":"1412da6b-b575-4645-8921-6669f13d"}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mp-prod.appsmb.com:443 "POST /mas/v5/app/proxy?alias=/mj/user/login HTTP/1.1" 200 867
DEBUG:msmart.cloud:Response: {"code":0,"msg":"成功","data":{"randomData":"73d250fc7a7d47155e4bcefd5870833b98101e2ba600980f9f9749eab71df9c7","uid":"93d06a9f1cb9d91dc10f13e72093db55","accountId":"3276838999","nickname":"midea_is_best@outlook.com","mdata":{"tokenPwdInfo":{"tokenPwd":"27861863919f413eb985e1cdc82d110f","expiredDate":1656602908887,"createDate":1654010908887},"userInfo":{"sourceId":"mj_12345","empId":"4732773915458560","address":"","gender":"0","mobile":"midea_is_best@outlook.com","userDeptInfoList":null,"extras":null,"nameEn":null,"employeeNumber":null,"headPhoto":null,"uid":"93d06a9f1cb9d91dc10f13e72093db55","name":"midea_is_best@outlook.com","email":null},"doDeviceBind":null,"accessToken":"T1b5bpokcruo4ohbh","signUnlockEnabled":null},"accessToken":"d58ca088d185a136e84fb6224d8f87ecfb0a9b85167db0bd2dad39b0246eb0d4","userId":"5496469","email":"midea_is_best@outlook.com"}}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mp-prod.appsmb.com:443
DEBUG:urllib3.connectionpool:https://mp-prod.appsmb.com:443 "POST /mas/v5/app/proxy?alias=/v1/iot/secure/getToken HTTP/1.1" 200 None
DEBUG:msmart.cloud:Response: {"msg":"ok","code":"0","data":{"tokenlist":[{"udpId":"6335ee2b5f498cb684ece6449f9ef373","key":"FAEF7488E8C04F979B479CA3C02911D1ABD7B819E3464DB5A13F4406486CF206","token":"154A8D1870E21DC2A9EDEB200B9D36D7E14B77CD3D6F792C52800A55B0B06ED125FB284B6B9F8A561C816874ABF03E00BDA5526237FBB9327C838CCA9379B59A"}]}}
DEBUG:msmart.lan:Attempting new connection to 192.168.2.103:6444
DEBUG:msmart.lan:Socket 192.168.2.87:63902 -> 192.168.2.103:6444 retries: 0 time: 0.0 tcp_key: None
DEBUG:msmart.lan:Sending 192.168.2.87:63902 -> 192.168.2.103:6444 retries: 0 time: 0.0 message: 8370004020000000154a8d1870e21dc2a9edeb200b9d36d7e14b77cd3d6f792c52800a55b0b06ed125fb284b6b9f8a561c816874abf03e00bda5526237fbb9327c838cca9379b59a
DEBUG:msmart.lan:Recv 192.168.2.87:63902 -> 192.168.2.103:6444 retries: 0 time: 0.51 Response: 83700040200100003ad4c895d854a162d6057d4baddbd28a4f959c39d76cb710a93f23e131a8ece35e584e47b04f11996168022b474447ca3286aa060d5958c0d2edace34bb6a493
Traceback (most recent call last):
  File "/Users/kezz/anaconda3/bin/midea-discover", line 8, in <module>
    sys.exit(discover())
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/cli.py", line 45, in discover
    found_devices = loop.run_until_complete(discovery.get_all() if ip == '' else discovery.get(ip))
  File "/Users/kezz/anaconda3/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/scanner.py", line 193, in get_all
    await self._process_tasks(tasks)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/scanner.py", line 199, in _process_tasks
    [self.result.add(task.result()) for task in tasks]
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/scanner.py", line 199, in <listcomp>
    [self.result.add(task.result()) for task in tasks]
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/scanner.py", line 50, in support_test
    _device = await self.support_testv3(account, password)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/scanner.py", line 66, in support_testv3
    auth = await loop.run_in_executor(None, _device.authenticate, key, token)
  File "/Users/kezz/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/device/base.py", line 38, in authenticate
    return self._authenticate()
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/device/base.py", line 42, in _authenticate
    return self._lan_service.authenticate(self._token, self._key)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/lan.py", line 113, in authenticate
    tcp_key, success = self.security.tcp_key(response, self._key)
  File "/Users/kezz/anaconda3/lib/python3.7/site-packages/msmart/security.py", line 103, in tcp_key
    self._tcp_key = strxor(plain, key)
TypeError: argument 2 must be bytes, not bytearray```

**Comment by jacob2826** [comment]
Problem solved by using Win10 + Python3.10 + without any arguments.

Perhaps, the error is due to the environment?
